create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 80),
  content text not null check (char_length(content) between 1 and 500),
  author_id uuid not null references auth.users(id),
  published boolean not null default true,
  published_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.news enable row level security;
alter table public.admin_users enable row level security;

create policy "Admins can read their own role"
  on public.admin_users for select
  to authenticated
  using (user_id = auth.uid());

create policy "Anyone can read published news"
  on public.news for select
  using (published = true);

create policy "Admins can create news"
  on public.news for insert
  to authenticated
  with check (
    exists (
      select 1 from public.admin_users
      where user_id = auth.uid()
    )
  );
